### ISSUE TITLE
How to label our sprints

### ISSUE THREAD

**Issue by nfode** [nfode/TOSCAna#11]
Talking with @hnicke the question appeared how do we show which issues belongs to a specific sprint.
@hnicke suggested to create milestones to label them.
I thought of creating a `sprint_n` label. 
What is your oppinion?

**Comment by mmunozba** [comment]
Milestones are probably the most clear option to show what issues belong to which sprint.
They also allow to set a due date and use features like velocity tracking to analyse sprint progress.

Having a milestone for every sprint might get a little confusing though, especially for other people looking into this repo. It might also confuse people because currently we plan to do normal milestones as well (e.g. after the completion of the AWS pugin). It might be a good idea to just set a release (or pre release) when we finish a big milestone (not sprints).

In my opinion using milestones would provide valid benefits over just using labels.

**Comment by mmunozba** [comment]
Any other opinions on this?

**Comment by mmunozba** [comment]
We have decided to use milestones.
